# Generated by Django 3.1.3 on 2021-01-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('camera_num', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Visiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photographs')),
            ],
        ),
        migrations.CreateModel(
            name='DataMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('camera_map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_manager.cameramap')),
                ('visiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db_manager.visiter')),
            ],
        ),
    ]
